# Generated by Django 4.1.4 on 2022-12-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
